project_name: bluetuith
version: 2

builds:
  - env:
      - CGO_ENABLED=0
      - GO111MODULE=on
      - GOPROXY=https://proxy.golang.org

    ldflags:
      - -s -w -X github.com/darkhz/bluetuith/cmd.Version={{.Version}}@{{.ShortCommit}}

    goos:
      - linux

    goarch:
      - arm
      - 386
      - arm64
      - amd64

    goarm:
      - 5
      - 6
      - 7

archives:
  - id: foo
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else if eq .Arch "arm" }}{{ .Arch }}v{{ .Arm }}
      {{- else }}{{ .Arch }}{{ end }}

    files:
      - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  disable: true
